# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 10:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.CharField(choices=[('BR', 'Breakfast'), ('LA', 'Launch'), ('DI', 'Dinner'), ('DE', 'Delivery'), ('CA', 'Cafe'), ('LU', 'Luxury Dining'), ('NI', 'Night Life')], default='DI', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of the meal', max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('price', models.IntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, upload_to='upload/restaurant/meal/%Y/%m/%d')),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of the category of meal', max_length=80)),
                ('slug', models.SlugField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of restaurant', max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(help_text='name of city where restaurant is', max_length=80)),
                ('phone_number', models.PositiveIntegerField()),
                ('owner_email', models.EmailField(max_length=254)),
                ('image', models.ImageField(blank=True, upload_to='upload/restaurant/%Y/%m/%d')),
                ('other_detail', models.TextField(blank=True, help_text='detail about your restaurant', null=True)),
                ('website', models.URLField()),
                ('status', models.IntegerField(choices=[(1, 'open'), (2, 'closed')], default=1, help_text='status of your restaurant')),
                ('facebook_page', models.URLField(blank=True, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=15, null=True)),
                ('is_parking', models.BooleanField(default=False)),
                ('is_wifi', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('features', models.ManyToManyField(to='restaurants.Feature')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timings', models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], default='MO', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='timings',
            field=models.ManyToManyField(to='restaurants.Timing'),
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.MealCategory'),
        ),
        migrations.AddField(
            model_name='meal',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant'),
        ),
    ]
