# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealcategory',
            options={'verbose_name': 'Meal Category', 'verbose_name_plural': 'Meal Categories'},
        ),
        migrations.AddField(
            model_name='meal',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
